### ISSUE TITLE
Questions about experimental result

### ISSUE THREAD

**Issue by aixiaodewugege** [M-Nauta/TCDF#10]

**Comment by M-Nauta** [comment]
The results in Table 4 of the paper are the average over _all datasets_ in the Finance and fMRI folders. I just ran the following commands again with the default parameters (except for the number of epochs which is set to 5000 as also mentioned in the paper) and got similar results as reported in the paper (even higher F1 scores for fMRI). Note that results might differ slightly with different random seeds and due to some [randomness](https://pytorch.org/docs/stable/notes/randomness.html) in PyTorch executions. 

Finance:
`runTCDF.py --cuda --epochs 5000 --ground_truth data/Finance/random-rels_20_1A_returns30007000_header.csv=data/Finance/random-rels_20_1A.csv,data/Finance/random-rels_20_1B_returns30007000_header.csv=data/Finance/random-rels_20_1B.csv,data/Finance/random-rels_20_1C_returns30007000_header.csv=data/Finance/random-rels_20_1C.csv,data/Finance/random-rels_20_1D_returns30007000_header.csv=data/Finance/random-rels_20_1D.csv,data/Finance/random-rels_20_1E_returns30007000_header.csv=data/Finance/random-rels_20_1E.csv,data/Finance/random-rels_20_1_3_returns30007000_header.csv=data/Finance/random-rels_20_1_3.csv,data/Finance/random-rels_40_1_3_returns30007000_header.csv=data/Finance/random-rels_40_1_3.csv,data/Finance/random-rels_40_1_returns30007000_header.csv=data/Finance/random-rels_40_1.csv,data/Finance/manyinputs_returns30007000_header.csv=data/Finance/manyinputs.csv`

fMRI:
`runTCDF.py --cuda --epochs 5000 --ground_truth data/fMRI/timeseries1.csv=data/fMRI/sim1_gt_processed.csv,data/fMRI/timeseries2.csv=data/fMRI/sim2_gt_processed.csv,data/fMRI/timeseries3.csv=data/fMRI/sim3_gt_processed.csv,data/fMRI/timeseries5.csv=data/fMRI/sim5_gt_processed.csv,data/fMRI/timeseries6.csv=data/fMRI/sim6_gt_processed.csv,data/fMRI/timeseries7.csv=data/fMRI/sim7_gt_processed.csv,data/fMRI/timeseries8.csv=data/fMRI/sim8_gt_processed.csv,data/fMRI/timeseries9.csv=data/fMRI/sim9_gt_processed.csv,data/fMRI/timeseries10.csv=data/fMRI/sim10_gt_processed.csv,data/fMRI/timeseries11.csv=data/fMRI/sim11_gt_processed.csv,data/fMRI/timeseries12.csv=data/fMRI/sim12_gt_processed.csv,data/fMRI/timeseries13.csv=data/fMRI/sim13_gt_processed.csv,data/fMRI/timeseries14.csv=data/fMRI/sim14_gt_processed.csv,data/fMRI/timeseries15.csv=data/fMRI/sim15_gt_processed.csv,data/fMRI/timeseries16.csv=data/fMRI/sim16_gt_processed.csv,data/fMRI/timeseries17.csv=data/fMRI/sim17_gt_processed.csv,data/fMRI/timeseries18.csv=data/fMRI/sim18_gt_processed.csv,data/fMRI/timeseries19.csv=data/fMRI/sim19_gt_processed.csv,data/fMRI/timeseries20.csv=data/fMRI/sim20_gt_processed.csv,data/fMRI/timeseries21.csv=data/fMRI/sim21_gt_processed.csv,data/fMRI/timeseries22.csv=data/fMRI/sim22_gt_processed.csv,data/fMRI/timeseries23.csv=data/fMRI/sim23_gt_processed.csv,data/fMRI/timeseries24.csv=data/fMRI/sim24_gt_processed.csv,data/fMRI/timeseries25.csv=data/fMRI/sim25_gt_processed.csv,data/fMRI/timeseries26.csv=data/fMRI/sim26_gt_processed.csv,data/fMRI/timeseries27.csv=data/fMRI/sim27_gt_processed.csv,data/fMRI/timeseries28.csv=data/fMRI/sim28_gt_processed.csv`
