### ISSUE TITLE
How to plot the predicted time series ? / How to print time delays in cause and effect ? (new to python)

### ISSUE THREAD

**Issue by zzadiues3338** [M-Nauta/TCDF#11]
Howdy , 
I am new to python and found your code extremely useful and I am trying to implement to my dataset. 

I went through the documents and it is not clear to me how to plot the predicted time series ? 

additionally, how can I print the computed values of time delays in cause and effect? 

Thank you very much for your time and consideration. 

Sincerely, 
Aditya Chakravarty

**Comment by M-Nauta** [comment]
Hi Aditya,
As shown in the demo file, the time series can be plotted by running `evaluate_predictions_TCDF.py` with argument `--plot`. The time delays between cause and effect are automatically printed when running `runTCDF.py`. To run TCDF on your own dataset, you simply have to set the path to the csv file as `--data` argument. Since you're new to python, I would recommend to do a python tutorial if you want to adapt the code to do something else. Good luck! :)
